global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'predict_api'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'lstm_monitoring'
    static_configs:
      - targets: ['monitoring_app:9100']
